# -*- coding: utf-8 -*-
"""Q1_Narra_FA1_Canolas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0anBAjehk9G32WOPW7T-ruyEvPHextD
"""

import math
x1=float(input("enter x1:"))
y1=float(input("enter y1:"))
x2=float(input("enter x2:"))
y2=float(input("enter y2:"))

d=math.sqrt((x2-x1)**2+(y2-y1)**2)
print(d)

#simple it assist me ahead of time to understand that everthing is already there for me to use, not to memorize all meanings. By the math library it has given me tools to write auto correct the spelling and same as math in paper.


#Guide Questions:

#How did the math library help simplify your program? / BY SHOWING ME THE MEANING OF EACH FUNCTIONS SO THAT I WONT OVERTHINK THE DIFFERENTS
#What functions were easier to use because of the library? /sqrt()
#How would the program be more difficult without sqrt() and pow()? / IM NOT SURE DUE TO THE FACT I LACK THE EXPERIENCE IN THIS DEPARTMENT OF FULLY UNDERSTANDING